name: ''
description: ''
inputs:
  RESOURCE_GROUP:
    required: true
    description: ""
  CONTAINER_APP:
    required: true
    description: ""
  CONTAINER_REGISTRY:
    required: true
    description: ""
  IMAGE:
    required: true
    description: ""
  MULTI_REVISION:
    required: false
    description: ""
    default: "false"

runs:
  using: "composite"
  steps:    
    - name: Create new revision of Container App
      uses: azure/cli@v2
      with:
        inlineScript: |
          echo Creating new revision of ${{ inputs.CONTAINER_APP }}...
          az containerapp revision copy \
            --resource-group ${{ inputs.RESOURCE_GROUP }} \
            --name ${{ inputs.CONTAINER_APP }} \
            --image ${{ inputs.CONTAINER_REGISTRY }}/${{ inputs.IMAGE }}:${{ github.run_id }} \
            --revision-suffix run-${{ github.run_id }}

    - name: If using a multi-revision setup, ensure that 100% of traffic is set to the latest...
      uses: azure/cli@v2
      if: inputs.MULTI_REVISION == 'true'
      with:
        inlineScript: |
          echo Ensuring latest revision gets 100% of traffic...
          az containerapp ingress traffic set \
            --resource-group ${{ inputs.RESOURCE_GROUP }} \
            --name ${{ inputs.CONTAINER_APP }} \
            --revision-weight latest=100
