name: ''
description: ''
inputs:
  RESOURCE_GROUP:
    required: true
    description: ""
  CONTAINER_APP:
    required: true
    description: ""
  CONTAINER_REGISTRY:
    required: true
    description: ""
  IMAGE:
    required: true
    description: ""
  MULTI_REVISION:
    required: false
    description: ""
    default: "false"
  SERVICE_PRINCIPAL_ID:
    required: true
    description: ""
  SERVICE_PRINCIPAL_PASSWORD:
    required: true
    description: ""
  TENANT:
    required: true
    description: ""
  SUBSCRIPTION:
    required: true
    description: ""

runs:
  using: "composite"
  steps:    
    - name: Log in to Azure
      uses: ./reusable-workflow/.github/actions/azure-login
      with:
        SERVICE_PRINCIPAL_ID: ${{ inputs.SERVICE_PRINCIPAL_ID }}
        SERVICE_PRINCIPAL_PASSWORD: ${{ inputs.SERVICE_PRINCIPAL_PASSWORD }}
        TENANT: ${{ inputs.TENANT }}
        SUBSCRIPTION: ${{ inputs.SUBSCRIPTION }}

    - name: Create new revision of Container App
      uses: azure/cli@v2
      with:
        inlineScript: |
          echo Creating new revision of ${{ inputs.CONTAINER_APP }}...
          az containerapp revision copy \
            --resource-group ${{ inputs.RESOURCE_GROUP }} \
            --name ${{ inputs.CONTAINER_APP }} \
            --image ${{ inputs.CONTAINER_REGISTRY }}/${{ inputs.IMAGE }}:${{ github.run_id }} \
            --revision-suffix run-${{ github.run_id }}

    - name: If using a multi-revision setup, ensure that 100% of traffic is set to the latest...
      uses: azure/cli@v2
      if: inputs.MULTI_REVISION == 'true'
      with:
        inlineScript: |
          echo Ensuring latest revision gets 100% of traffic...
          az containerapp ingress traffic set \
            --resource-group ${{ inputs.RESOURCE_GROUP }} \
            --name ${{ inputs.CONTAINER_APP }} \
            --revision-weight latest=100
