name: "Azure Login"
description: "Logs in to Azure using the provided Service Principal credentials"
inputs:
  TENANT:
    required: true
    description: "ID of the Azure tenant to log in to"
  SUBSCRIPTION:
    required: true
    description: "ID of the Azure subscription to log in to"
  SERVICE_PRINCIPAL_ID:
    required: true
    description: "The ID of the Service Principal in Azure that will be used to log in"
  SERVICE_PRINCIPAL_PASSWORD:
    required: true
    description: "The password for the Service Principal in Azure"

runs:
  using: "composite"
  steps:
    - name: Build Azure credentials JSON object
      shell: bash
      run: |
        az login --service-principal \
          --username "${{ inputs.SERVICE_PRINCIPAL_ID }}" \
          --password "${{ inputs.SERVICE_PRINCIPAL_PASSWORD }}" \
          --tenant "${{ inputs.TENANT }}"
        az account set --subscription "${{ inputs.SUBSCRIPTION }}"