name: "Push Docker Image"
description: "Pushes a Docker image to a Container Registry"
inputs:
  CONTAINER_REGISTRY:
    required: false
    description: "The Docker registry to log in to"
  CONTAINER_REGISTRY_USERNAME:
    required: false
    description: "The registry username"
  CONTAINER_REGISTRY_PASSWORD:
    required: false
    description: "The registry password"
  BUILD_TAG:
    required: true
    description: "Tag that was used to build the Docker image, simply for reference purposes"
  PUSH_TAGS:
    required: true
    description: "A space-separated list of tags to push the Docker image with"

runs:
  using: "composite"
  steps:
    - name: Log in to Container Registry ${{ inputs.CONTAINER_REGISTRY }}
      if: inputs.CONTAINER_REGISTRY != ''
      shell: bash
      run: |
        if ! docker system info | grep -q "Username:"; then
          echo "${{ inputs.CONTAINER_REGISTRY_PASSWORD }}" \
            | docker login ${{ inputs.CONTAINER_REGISTRY }} \
              -u ${{ inputs.CONTAINER_REGISTRY_USERNAME }} --password-stdin
        else
          echo "Already logged in, skipping"
        fi

    - name: Push Docker image
      shell: bash
      run: |
        docker tag ${{ inputs.BUILD_TAG }} ${{ inputs.PUSH_TAGS }}
        docker push ${{ inputs.PUSH_TAGS }}

