name: "Trivy Scan"
description: "Scans Docker images for vulnerabilities using Trivy"
inputs:
  IMAGE_REF:
    required: true
    description: "The Docker image reference (e.g. my-image:latest) to scan"

runs:
  using: "composite"
  steps:
    - name: Trivy scan
      uses: aquasecurity/trivy-action@v0.10.7
      with:
        image-ref: ${{ inputs.IMAGE_REF }}
        format: 'table'
        exit-code: '1'
        severity: 'CRITICAL,HIGH'
        ignore-unfixed: 'true'
