name: Run e2e Tests
description: Runs end-to-end tests

inputs:
  INIT_DOCKERFILE:
    description: 'Path to the Dockerfile used for building the init image'
    required: true
  INIT_DOCKERFILE_TARGET:
    description: 'Target stage in the Dockerfile for the init image'
    required: true
  PHP_DOCKERFILE:
    description: 'Path to the Dockerfile used for building the PHP image'
    required: true
  PHP_DOCKERFILE_TARGET:
    description: 'Target stage in the Dockerfile for the PHP image'
    required: true
  PIMCORE_ROOT:
    description: 'Path to the Pimcore root directory (relative to project root)'
    required: true
  TESTS_DIRECTORY:
    description: 'Path to e2e test files'
    required: true
  NODE_VERSION:
    description: 'Node.js version to use'
    required: true
  PIMCORE_ENTERPRISE_TOKEN:
    required: false
    description: (Optional) The value of your project's Pimcore Enterprise Token
  PIMCORE_PRODUCT_KEY:
    required: false
    description: (Optional) The Pimcore product key for the project
  PIMCORE_INSTANCE_IDENTIFIER:
    required: false
    description: (Optional) The Pimcore instance identifier for the project
  PIMCORE_ENCRYPTION_SECRET:
    required: false
    description: (Optional) The Pimcore encryption secret for the project
  BUILD_TIME_SECRETS:
    required: false
    description: 'A JSON object containing a list of build-time secrets in key: value format'
    default: '{}'
  RUN_TIME_SECRETS:
    required: false
    description: 'A JSON object containing a list of run-time secrets in key: value format'
    default: '{}'
  HOSTNAME:
    description: 'Hostname to add to /etc/hosts'
    required: true
  PHP_DOCKER_COMPOSE_SERVICE:
    description: 'Name of the PHP service in Docker Compose'
    required: true
  E2E_DOCKER_COMPOSE_SERVICE:
    description: 'Name of the e2e tests service in Docker Compose'
    required: true
  GITHUB_TOKEN:
    description: 'GitHub token used for adding results to PRs'
    required: false
    default: ''
  PR_NUMBER:
    description: 'Pull Request number to post results to'
    required: false
    default: ''

runs:
  using: "composite"
  steps:
    - name: Build init image
      uses: ./reusable-workflow/.github/actions/build-and-push-pimcore-image
      with:
        DOCKERFILE_PATH: ${{ inputs.INIT_DOCKERFILE }}
        DOCKERFILE_TARGET: ${{ inputs.INIT_DOCKERFILE_TARGET }}
        PIMCORE_ROOT: ${{ inputs.PIMCORE_ROOT }}
        BUILD_TIME_ARGS: ${{ inputs.BUILD_TIME_ARGS }}
        BUILD_TIME_SECRETS: ${{ inputs.BUILD_TIME_SECRETS }} 
        PIMCORE_ENTERPRISE_TOKEN: ${{ inputs.PIMCORE_ENTERPRISE_TOKEN }}
        PIMCORE_PRODUCT_KEY: ${{ inputs.PIMCORE_PRODUCT_KEY }}
        PIMCORE_INSTANCE_IDENTIFIER: ${{ inputs.PIMCORE_INSTANCE_IDENTIFIER }}
        PIMCORE_ENCRYPTION_SECRET: ${{ inputs.PIMCORE_ENCRYPTION_SECRET }}
        PUSH: "false"
        LOAD: "true"
        TAGS: "init:latest"

    - name: Build PHP image
      uses: ./reusable-workflow/.github/actions/build-and-push-pimcore-image
      with:
        DOCKERFILE_PATH: ${{ inputs.PHP_DOCKERFILE }}
        DOCKERFILE_TARGET: ${{ inputs.PHP_DOCKERFILE_TARGET }}
        PIMCORE_ROOT: ${{ inputs.PIMCORE_ROOT }}
        BUILD_TIME_ARGS: ${{ inputs.BUILD_TIME_ARGS }}
        BUILD_TIME_SECRETS: ${{ inputs.BUILD_TIME_SECRETS }} 
        PIMCORE_ENTERPRISE_TOKEN: ${{ inputs.PIMCORE_ENTERPRISE_TOKEN }}
        PIMCORE_PRODUCT_KEY: ${{ inputs.PIMCORE_PRODUCT_KEY }}
        PIMCORE_INSTANCE_IDENTIFIER: ${{ inputs.PIMCORE_INSTANCE_IDENTIFIER }}
        PIMCORE_ENCRYPTION_SECRET: ${{ inputs.PIMCORE_ENCRYPTION_SECRET }}
        PUSH: "false"
        LOAD: "true"
        TAGS: "php:latest"

    - name: Build e2e image
      uses: ./reusable-workflow/.github/actions/build-and-push-pimcore-image
      with:
        DOCKERFILE_PATH: ${{ inputs.TESTS_DIRECTORY }}/Dockerfile
        PUSH: "false"
        LOAD: "true"
        TAGS: "e2e:latest"

    - name: Prepare run-time secrets directory
      shell: bash
      run: mkdir -p .secrets

    - name: Create necessary run-time secret files
      shell: bash
      run: |
        echo -n "$(openssl rand -hex 16)" > .secrets/kernel-secret
        echo "::add-mask::${{ inputs.PIMCORE_ENTERPRISE_TOKEN }}"
        echo -n "${{ inputs.PIMCORE_ENTERPRISE_TOKEN }}" > .secrets/pimcore-enterprise-token
        echo "::add-mask::${{ inputs.PIMCORE_PRODUCT_KEY }}"
        echo -n "${{ inputs.PIMCORE_PRODUCT_KEY }}" > .secrets/pimcore-product-key
        echo "::add-mask::${{ inputs.PIMCORE_INSTANCE_IDENTIFIER }}"
        echo -n "${{ inputs.PIMCORE_INSTANCE_IDENTIFIER }}" > .secrets/pimcore-instance-identifier
        echo "::add-mask::${{ inputs.PIMCORE_ENCRYPTION_SECRET }}"
        echo -n "${{ inputs.PIMCORE_ENCRYPTION_SECRET }}" > .secrets/pimcore-encryption-secret

    - name: Write run-time secrets to files
      shell: bash
      run: |
        set -e
        JSON_INPUT='${{ inputs.RUN_TIME_SECRETS }}'
        echo "$JSON_INPUT" | jq -r 'to_entries[] | "\(.key)=\(.value)"' | while IFS='=' read -r key value; do
          echo "::add-mask::$value"
          echo "$value" >> .secrets/$key
        done

    - name: Overwrite run-tests.sh
      shell: bash
      run: |
        echo "set -e; npx playwright test" > ${{ inputs.TESTS_DIRECTORY }}/run-tests.sh

    - name: Start Docker containers
      shell: bash
      run: |
        set -e
        docker compose up --no-build init
        NGINX_FILE=".docker/php/nginx.conf" docker compose up --no-build ${{ inputs.PHP_DOCKER_COMPOSE_SERVICE }} -d --no-deps
        docker compose up \
          --no-build \
          --no-deps \
          --abort-on-container-exit \
          --exit-code-from ${{ inputs.E2E_DOCKER_COMPOSE_SERVICE }} \
          ${{ inputs.E2E_DOCKER_COMPOSE_SERVICE }}

    - name: Stop Docker containers
      if: always()
      shell: bash
      run: docker compose down -v

    - name: Clean up secrets
      if: always()
      shell: bash
      run: rm -rf .secrets

    - name: Remove Docker image cache
      if: always()
      shell: bash
      run: rm -rf /tmp/docker-images
