name: Run e2e Tests
description: Runs end-to-end tests

inputs:
  TESTS_DIRECTORY:
    description: 'Path to e2e test files'
    required: true
  NODE_VERSION:
    description: 'Node.js version to use'
    required: true
  PIMCORE_ENTERPRISE_TOKEN:
    required: false
    description: (Optional) The value of your project's Pimcore Enterprise Token
  PIMCORE_PRODUCT_KEY:
    required: false
    description: (Optional) The Pimcore product key for the project
  PIMCORE_INSTANCE_IDENTIFIER:
    required: false
    description: (Optional) The Pimcore instance identifier for the project
  PIMCORE_ENCRYPTION_SECRET:
    required: false
    description: (Optional) The Pimcore encryption secret for the project
  BUILD_TIME_SECRETS:
    required: false
    description: 'A JSON object containing a list of build-time secrets in key: value format'
    default: '{}'
  RUN_TIME_SECRETS:
    required: false
    description: 'A JSON object containing a list of run-time secrets in key: value format'
    default: '{}'
  HOSTNAME:
    description: 'Hostname to add to /etc/hosts'
    required: true
  PHP_DOCKER_COMPOSE_SERVICE:
    description: 'Name of the PHP service in Docker Compose'
    required: true
  E2E_DOCKER_COMPOSE_SERVICE:
    description: 'Name of the e2e tests service in Docker Compose'
    required: true
  GITHUB_TOKEN:
    description: 'GitHub token used for adding results to PRs'
    required: false
    default: ''
  PR_NUMBER:
    description: 'Pull Request number to post results to'
    required: false
    default: ''

runs:
  using: "composite"
  steps:
    - name: Add host entry
      shell: bash
      if: inputs.HOSTNAME != ''
      run: echo "127.0.0.1 ${{ inputs.HOSTNAME }}" | sudo tee -a /etc/hosts

    - name: Prepare secrets directory
      shell: bash
      run: mkdir -p .secrets

    - name: Create necessary secret files
      shell: bash
      run: |
        echo -n "$(openssl rand -hex 16)" > .secrets/kernel-secret
        echo "::add-mask::${{ inputs.PIMCORE_ENTERPRISE_TOKEN }}"
        echo -n "${{ inputs.PIMCORE_ENTERPRISE_TOKEN }}" > .secrets/pimcore-enterprise-token
        echo "::add-mask::${{ inputs.PIMCORE_PRODUCT_KEY }}"
        echo -n "${{ inputs.PIMCORE_PRODUCT_KEY }}" > .secrets/pimcore-product-key
        echo "::add-mask::${{ inputs.PIMCORE_INSTANCE_IDENTIFIER }}"
        echo -n "${{ inputs.PIMCORE_INSTANCE_IDENTIFIER }}" > .secrets/pimcore-instance-identifier
        echo "::add-mask::${{ inputs.PIMCORE_ENCRYPTION_SECRET }}"
        echo -n "${{ inputs.PIMCORE_ENCRYPTION_SECRET }}" > .secrets/pimcore-encryption-secret

    - name: Write run-time secrets to files
      shell: bash
      run: |
        set -e
        JSON_INPUT='${{ inputs.RUN_TIME_SECRETS }}'
        echo "$JSON_INPUT" | jq -r 'to_entries[] | "\(.key)=\(.value)"' | while IFS='=' read -r key value; do
          echo "::add-mask::$value"
          echo "$value" >> .secrets/$key
        done

    - name: Overwrite run-tests.sh
      shell: bash
      run: |
        echo "set -e; npx playwright test" > ${{ inputs.TESTS_DIRECTORY }}/run-tests.sh

    - name: Set environment variables
      shell: bash
      run: |
        echo "DOCKER_BUILDKIT=1" >> $GITHUB_ENV
        echo "COMPOSE_DOCKER_CLI_BUILD=1" >> $GITHUB_ENV

    - name: Restore cached Docker images
      uses: actions/cache@v3
      with:
        path: /tmp/docker-images
        key: docker-images-${{ runner.os }}-v1

    - name: Load Docker images if cache exists
      shell: bash
      run: |
        if [ -d /tmp/docker-images ]; then
          for f in /tmp/docker-images/*.tar; do
            docker load -i "$f"
          done
        fi

    - name: Build Docker images 
      shell: bash
      run: |
        PHP_SERVICE="${{ inputs.PHP_DOCKER_COMPOSE_SERVICE }}"
        E2E_SERVICE="${{ inputs.E2E_DOCKER_COMPOSE_SERVICE }}"

        docker compose build \
          --progress=plain \
          --build-arg UID=$(id -u $USER) \
          --build-arg GID=$(id -g $USER) \
          init $PHP_SERVICE $E2E_SERVICE

    - name: Save Docker images to cache
      shell: bash
      run: |
        mkdir -p /tmp/docker-images
        docker save ${{ inputs.PHP_DOCKER_COMPOSE_SERVICE }}:latest -o /tmp/docker-images/php.tar
        docker save init:latest -o /tmp/docker-images/init.tar
        docker save ${{ inputs.E2E_DOCKER_COMPOSE_SERVICE }}:latest -o /tmp/docker-images/e2e.tar

    - name: Persist Docker image cache
      uses: actions/cache@v3
      with:
        path: /tmp/docker-images
        key: docker-images-${{ runner.os }}-v1

    - name: Start Docker containers
      shell: bash
      run: |
        set -e
        userId=$(id -u $USER)
        groupId=$(id -g $USER)
        docker compose up --no-build init
        NGINX_FILE=".docker/php/nginx.conf" docker compose up --no-build ${{ inputs.PHP_DOCKER_COMPOSE_SERVICE }} -d --no-deps
        docker compose up --no-build ${{ inputs.E2E_DOCKER_COMPOSE_SERVICE }} --no-deps

    - name: Stop Docker containers
      if: always()
      shell: bash
      run: docker compose down -v

    - name: Clean up secrets
      if: always()
      shell: bash
      run: rm -rf .secrets
