name: "Azure Apply Infrastructure Changes"
description: "Applies Azure infrastructure updates based on the given parameters file"
inputs:
  TENANT:
    required: true
    description: "ID of the Azure tenant to log in to"
  PARAMETERS_FILE:
    required: false
    description: "Azure parameters file path"
  SERVICE_PRINCIPAL_ID:
    required: true
    description: "The ID of the Service Principal in Azure that will be used to log in"
  SERVICE_PRINCIPAL_PASSWORD:
    required: true
    description: "The password for the Service Principal in Azure"

runs:
  using: "composite"
  steps:
    - name: Build and start container
      shell: bash
      run: |
        touch .env
        docker run \
          --name azure \
          -d \
          ghcr.io/torqit/pimcore-azure-provisioning:quick-provisioning

    - name: Log in to Azure inside container
      shell: bash
      run: |
        touch .env
        TENANT=$(jq -r '.parameters.tenantId.value' ${{ inputs.PARAMETERS_FILE }}) >> .env
        SERVICE_PRINCIPAL_ID=${{ inputs.SERVICE_PRINCIPAL_ID }} >> .env
        SERVICE_PRINCIPAL_PASSWORD=${{ inputs.SERVICE_PRINCIPAL_PASSWORD }} >> .env
        docker exec \
          --env-file .env \
          azure \
            az login --tenant $TENANT \
              --service-principal \
                --username $SERVICE_PRINCIPAL_ID \
                --password $SERVICE_PRINCIPAL_PASSWORD

    - name: Apply infrastructure changes
      shell: bash
      run: |
        touch .env
        PARAMETERS_FILE=${{ inputs.PARAMETERS_FILE }}
        docker exec \
          --env-file .env \
          azure \
            ./provision-quick.sh $PARAMETERS_FILE