name: 'Copy Config Files'
description: 'Copy in common configuration files required for a Shopware deployment to Container Apps'
inputs:
  PHP_VERSION:
    required: true
    description: 'PHP version'
  SHOPWARE_ROOT:
    required: true
    description: 'Root of the Shopware files in the project'

runs:
  using: "composite"
  steps:
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '${{ inputs.PHP_VERSION }}'

    - name: Setup jq for parsing JSON
      uses: dcarbone/install-jq-action@v3
      with:
        version: '1.7'
        force: true

    - name: Replace local dependencies in composer.lock with remotes
      shell: bash
      run: |
        cd ${{ env.WORK_DIR }}/$SHOPWARE_ROOT
        ls -la
        packages=$(jq -r '.packages.[] | select(.dist.type=="path") | "composer require " + .name + ":" + .version' composer.lock)
        IFS=$'\n'
        for package in $packages
        do
          eval "$package"
        done