name: "Copy Azure Flysystem Config Files"
description: "Copy in configuration files required when using Flysystem with Azure"
inputs:
  PIMCORE_ROOT:
    required: true
    description: "The path (relative to the project's root) in which the Pimcore files are stored (e.g. config, src, etc)"

runs:
  using: "composite"
  steps:
    - name: Copy in config files
      shell: bash
      run: cp ./reusable-workflow/.azure/config/packages/flysystem.yaml ${{ inputs.PIMCORE_ROOT }}/config/packages/flysystem.yaml

    - name: If the client repository contains its own config file, copy that in as well
      shell: bash
      run: |
        if [ -e ${{ inputs.PIMCORE_ROOT }}/config/flysystem/flysystem-dev-prod.yaml ]; then
          cp ${{ inputs.PIMCORE_ROOT }}/config/flysystem/flysystem-dev-prod.yaml ${{ inputs.PIMCORE_ROOT }}/config/packages/flysystem.yaml
        fi