name: ""
description: ""
inputs:
  CONTAINER_REGISTRY:
    required: false
    description: ""
  CONTAINER_REGISTRY_USERNAME:
    required: false
    description: ""
  CONTAINER_REGISTRY_PASSWORD:
    required: false
    description: ""

runs:
  using: "composite"
  steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Container Registry ${{ inputs.CONTAINER_REGISTRY }}
      if: inputs.CONTAINER_REGISTRY != ''
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.CONTAINER_REGISTRY }}
        username: "${{ inputs.CONTAINER_REGISTRY_USERNAME }}"
        password: "${{ inputs.CONTAINER_REGISTRY_PASSWORD }}"