parameters:
  env(DATABASE_SERVER_VERSION): '8.0'
doctrine:
  dbal:
    connections:
      default:
        host: "%env(string:DATABASE_HOST)%"
        port: "3306"
        user: "%env(string:DATABASE_USER)%"
        password: "%env(string:DATABASE_PASSWORD)%"
        dbname: "%env(string:DATABASE_NAME)%"
        mapping_types: { enum: string, bit: boolean }
        server_version: '%env(DATABASE_SERVER_VERSION)%'
        options:
          !php/const:PDO::MYSQL_ATTR_SSL_CA: '/var/www/html/config/db/DigiCertGlobalRootCA.crt.pem'
          1001: true
