# Builds, tags, and pushes Pimcore Docker images to an Azure Container Registry, and deploys them to Container Apps.
#
# Requires the following permissions to be set in the callig job:
# permissions:
#   contents: read
#   actions: read

name: Build, tag, and push Docker images, and deploy to Azure Container Apps

on:
  workflow_call:
    inputs:
      RUNNER:
        required: false
        type: string
      NPM_BUILD:
        required: false
        type: boolean
      NPM_RUN_CMD:
        required: false
        type: string
      NPM_SPA:
        required: false
        type: boolean
      SPA_TWIG:
        required: false
        type: string
        default: "default/default.html.twig"
      ENVIRONMENT:
        required: true
        type: string
      SUBMODULES:
        required: false
        type: boolean
        default: false
      PIMCORE_ROOT:
        required: false
        type: string
        default: "pimcore-root"
      PHP_DOCKERFILE:
        required: false
        type: string
        default: "docker/php-fpm/Dockerfile"
      PHP_DOCKER_TARGET:
        required: false
        type: string
        default: ""
      SUPERVISORD_DOCKERFILE:
        required: false
        type: string
        default: "docker/supervisord/Dockerfile"
      SUPERVISORD_TARGET:
        required: false
        type: string
        default: ""
      INIT:
        required: false
        type: boolean
        description: "DEPRECATED"

    secrets:
      SERVICE_PRINCIPAL_ID:
        required: true
      SERVICE_PRINCIPAL_PASSWORD:
        required: true
      PIMCORE_ENTERPRISE_TOKEN:
        required: false
      ENCRYPTION_SECRET:
        required: false
      TORQ_GITHUB_TOKEN:
        required: false
      RECAPTCHA_CLIENT_KEY:
        required: false

jobs:
  build-and-push-images-and-run-init:
    name: Build and push Pimcore Docker images, and run init job
    runs-on: ${{ inputs.RUNNER || 'ubuntu-latest' }}
    environment: ${{ inputs.ENVIRONMENT }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: ${{ inputs.SUBMODULES }}

      - name: Get workflow version
        id: workflow-version
        uses: canonical/get-workflow-version-action@v1
        with:
          repository-name: TorqIT/pimcore-github-actions-workflows
          file-name: container-apps-build-and-deploy.yml
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout workflow repository to use composite actions
        uses: actions/checkout@v4
        with:
          repository: TorqIT/pimcore-github-actions-workflows
          ref: ${{ steps.workflow-version.outputs.sha }}
          path: reusable-workflow
          fetch-depth: 1

      - name: Copy config files required for running in Azure
        uses: ./reusable-workflow/.github/actions/container-apps-copy-config
        with:
          PIMCORE_ROOT: ${{ inputs.PIMCORE_ROOT }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker
        uses: ./reusable-workflow/.github/actions/setup-docker
        with:
          CONTAINER_REGISTRY: ${{ vars.CONTAINER_REGISTRY }}
          CONTAINER_REGISTRY_USERNAME: ${{ secrets.SERVICE_PRINCIPAL_ID }}
          CONTAINER_REGISTRY_PASSWORD: ${{ secrets.SERVICE_PRINCIPAL_PASSWORD }}

      - name: Build and push init image
        uses: ./reusable-workflow/.github/actions/build-and-push-pimcore-image
        with:
          DOCKERFILE_PATH: ./.docker/Dockerfile
          DOCKERFILE_TARGET: init
          PIMCORE_ROOT: ${{ inputs.PIMCORE_ROOT }}
          PIMCORE_ENTERPRISE_TOKEN: ${{ secrets.PIMCORE_ENTERPRISE_TOKEN }}
          TORQ_GITHUB_TOKEN: ${{ secrets.TORQ_GITHUB_TOKEN }}
          CONTAINER_REGISTRY: ${{ vars.CONTAINER_REGISTRY }}
          IMAGE: ${{ vars.INIT_IMAGE }}
          CACHE_FROM: type=gha
          CACHE_TO: type=gha,mode=min

      - name: Build and push PHP image
        uses: ./reusable-workflow/.github/actions/build-and-push-pimcore-image
        with:
          DOCKERFILE_PATH: ${{ inputs.PHP_DOCKERFILE }}
          DOCKERFILE_TARGET: ${{ inputs.PHP_DOCKER_TARGET }}
          PIMCORE_ROOT: ${{ inputs.PIMCORE_ROOT }}
          PIMCORE_ENTERPRISE_TOKEN: ${{ secrets.PIMCORE_ENTERPRISE_TOKEN }}
          TORQ_GITHUB_TOKEN: ${{ secrets.TORQ_GITHUB_TOKEN }}
          CONTAINER_REGISTRY: ${{ vars.CONTAINER_REGISTRY }}
          IMAGE: ${{ vars.PHP_FPM_IMAGE }}
          NPM_BUILD: ${{ inputs.NPM_BUILD }}
          RECAPTCHA_CLIENT_KEY: ${{ secrets.RECAPTCHA_CLIENT_KEY }}
          NPM_SPA: ${{ inputs.NPM_SPA }}
          SPA_TWIG: ${{ inputs.SPA_TWIG }}
          NPM_RUN_CMD: ${{ inputs.NPM_RUN_CMD }}

      - name: Build and push supervisord image
        uses: ./reusable-workflow/.github/actions/build-and-push-pimcore-image
        with:
          SERVICE_PRINCIPAL_ID: ${{ secrets.SERVICE_PRINCIPAL_ID }}
          SERVICE_PRINCIPAL_PASSWORD: ${{ secrets.SERVICE_PRINCIPAL_PASSWORD }}
          TENANT: ${{ vars.TENANT }}
          SUBSCRIPTION: ${{ vars.AZURE_SUBSCRIPTION_ID }}
          DOCKERFILE_PATH: ${{ inputs.SUPERVISORD_DOCKERFILE }}
          DOCKERFILE_TARGET: ${{ inputs.SUPERVISORD_TARGET }}
          PIMCORE_ROOT: ${{ inputs.PIMCORE_ROOT }}
          PIMCORE_ENTERPRISE_TOKEN: ${{ secrets.PIMCORE_ENTERPRISE_TOKEN }}
          TORQ_GITHUB_TOKEN: ${{ secrets.TORQ_GITHUB_TOKEN }}
          CONTAINER_REGISTRY: ${{ vars.CONTAINER_REGISTRY }}
          IMAGE: ${{ vars.SUPERVISORD_IMAGE }}

      - name: Deploy and run init Container App Job
        uses: ./reusable-workflow/.github/actions/container-apps-deploy-and-run-init
        with:
          INIT_IMAGE: ${{ vars.INIT_IMAGE }}
          INIT_CONTAINER_APP_JOB: ${{ vars.INIT_CONTAINER_APP_JOB }}
          RESOURCE_GROUP: ${{ vars.RESOURCE_GROUP }}
          CONTAINER_REGISTRY: ${{ vars.CONTAINER_REGISTRY }}
    
  deploy-php-container-app-revision:
    name: Deploy new revision of PHP Container App
    runs-on: ${{ inputs.RUNNER || 'ubuntu-latest' }}
    environment: ${{ inputs.ENVIRONMENT }}
    needs:
      - build-and-push-images-and-run-init
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get workflow version
        id: workflow-version
        uses: canonical/get-workflow-version-action@v1
        with:
          repository-name: TorqIT/pimcore-github-actions-workflows
          file-name: container-apps-build-and-deploy.yml
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout workflow repository to use composite actions
        uses: actions/checkout@v4
        with:
          repository: TorqIT/pimcore-github-actions-workflows
          ref: ${{ steps.workflow-version.outputs.sha }}
          path: reusable-workflow
          fetch-depth: 1

      - name: Deploy new revision of Container App
        uses: ./reusable-workflow/.github/actions/container-apps-deploy-revision
        with:
          SERVICE_PRINCIPAL_ID: ${{ secrets.SERVICE_PRINCIPAL_ID }}
          SERVICE_PRINCIPAL_PASSWORD: ${{ secrets.SERVICE_PRINCIPAL_PASSWORD }}
          TENANT: ${{ vars.TENANT }}
          SUBSCRIPTION: ${{ vars.AZURE_SUBSCRIPTION_ID }}
          RESOURCE_GROUP: ${{ vars.RESOURCE_GROUP }}
          CONTAINER_REGISTRY: ${{ vars.CONTAINER_REGISTRY }}
          CONTAINER_APP: ${{ vars.PHP_FPM_CONTAINER_APP }}
          IMAGE: ${{ vars.PHP_FPM_IMAGE }}
          MULTI_REVISION: "true"

  # TODO using a matrix to de-duplicate these two jobs does not seem possible as we are using the "vars" context, which matrices seem to be unable to access (inputs appear empty)
  deploy-supervisord-container-app-revision:
    name: Deploy new revision of supervisord Container App
    runs-on: ${{ inputs.RUNNER || 'ubuntu-latest' }}
    environment: ${{ inputs.ENVIRONMENT }}
    needs:
      - build-and-push-images-and-run-init
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get workflow version
        id: workflow-version
        uses: canonical/get-workflow-version-action@v1
        with:
          repository-name: TorqIT/pimcore-github-actions-workflows
          file-name: container-apps-build-and-deploy.yml
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout workflow repository to use composite actions
        uses: actions/checkout@v4
        with:
          repository: TorqIT/pimcore-github-actions-workflows
          ref: ${{ steps.workflow-version.outputs.sha }}
          path: reusable-workflow
          fetch-depth: 1

      - name: Deploy new revision of Container App
        uses: ./reusable-workflow/.github/actions/container-apps-deploy-revision
        with:
          SERVICE_PRINCIPAL_ID: ${{ secrets.SERVICE_PRINCIPAL_ID }}
          SERVICE_PRINCIPAL_PASSWORD: ${{ secrets.SERVICE_PRINCIPAL_PASSWORD }}
          TENANT: ${{ vars.TENANT }}
          SUBSCRIPTION: ${{ vars.AZURE_SUBSCRIPTION_ID }}
          RESOURCE_GROUP: ${{ vars.RESOURCE_GROUP }}
          CONTAINER_REGISTRY: ${{ vars.CONTAINER_REGISTRY }}
          CONTAINER_APP: ${{ vars.SUPERVISORD_CONTAINER_APP }}
          IMAGE: ${{ vars.SUPERVISORD_IMAGE }}