# Builds, tags, and pushes Pimcore Docker images to an Azure Container Registry, and deploys them to Container Apps.
#
# Requires the following permissions to be set in the callig job:
# permissions:
#   contents: read
#   actions: read

name: Build, tag, and push Docker images, and deploy to Azure Container Apps

on:
  workflow_call:
    inputs:
      RUNNER:
        required: false
        type: string
      NPM_BUILD:
        required: false
        type: boolean
      NPM_RUN_CMD:
        required: false
        type: string
      NPM_SPA:
        required: false
        type: boolean
      SPA_TWIG:
        required: false
        type: string
        default: "default/default.html.twig"
      ENVIRONMENT:
        required: true
        type: string
      SUBMODULES:
        required: false
        type: boolean
        default: false
      INIT:
        required: false
        type: boolean
        default: false
      PIMCORE_ROOT:
        required: false
        type: string
        default: "pimcore-root"
      PHP_DOCKERFILE:
        required: false
        type: string
        default: "docker/php-fpm/Dockerfile"
      PHP_DOCKER_TARGET:
        required: false
        type: string
        default: ""
      SUPERVISORD_DOCKERFILE:
        required: false
        type: string
        default: "docker/supervisord/Dockerfile"
      SUPERVISORD_TARGET:
        required: false
        type: string
        default: ""

    secrets:
      SERVICE_PRINCIPAL_ID:
        required: true
      SERVICE_PRINCIPAL_PASSWORD:
        required: true
      PIMCORE_ENTERPRISE_TOKEN:
        required: false
      ENCRYPTION_SECRET:
        required: false
      TORQ_GITHUB_TOKEN:
        required: false
      RECAPTCHA_CLIENT_KEY:
        required: false

jobs:
  build-and-push-images:
    if: ${{ inputs.INIT }}
    runs-on: ${{ inputs.RUNNER || 'ubuntu-latest' }}
    environment: ${{ inputs.ENVIRONMENT }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get workflow version
        id: workflow-version
        uses: canonical/get-workflow-version-action@v1
        with:
          repository-name: TorqIT/pimcore-github-actions-workflows
          file-name: container-apps-build-and-deploy.yml
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout workflow repository to use composite actions
        uses: actions/checkout@v4
        with:
          repository: TorqIT/pimcore-github-actions-workflows
          ref: ${{ steps.workflow-version.outputs.sha }}
          path: reusable-workflow
          fetch-depth: 1

      - uses: ./reusable-workflow/.github/actions/container-apps-copy-config
        with:
          PIMCORE_ROOT: ${{ inputs.PIMCORE_ROOT }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: ./reusable-workflow/.github/actions/setup-docker
        with:
          CONTAINER_REGISTRY: ${{ vars.CONTAINER_REGISTRY }}
          CONTAINER_REGISTRY_USERNAME: ${{ secrets.SERVICE_PRINCIPAL_ID }}
          CONTAINER_REGISTRY_PASSWORD: ${{ secrets.SERVICE_PRINCIPAL_PASSWORD }}

      - name: Build and push init image
        uses: ./reusable-workflow/.github/actions/build-and-push-pimcore-image
        with:
          DOCKERFILE_PATH: ./.docker/Dockerfile
          DOCKERFILE_TARGET: init
          PIMCORE_ENTERPRISE_TOKEN: ${{ secrets.PIMCORE_ENTERPRISE_TOKEN }}
          TORQ_GITHUB_TOKEN: ${{ secrets.TORQ_GITHUB_TOKEN }}
          CONTAINER_REGISTRY: ${{ vars.CONTAINER_REGISTRY }}
          IMAGE: ${{ vars.INIT_IMAGE }}
          CACHE_FROM: type=gha
          CACHE_TO: type=gha,mode=max
          PIMCORE_ROOT: ${{ inputs.PIMCORE_ROOT }}

      - name: Build and push PHP image
        uses: ./reusable-workflow/.github/actions/build-and-push-pimcore-image
        with:
          DOCKERFILE_PATH: ./.docker/Dockerfile
          DOCKERFILE_TARGET: php
          PIMCORE_ENTERPRISE_TOKEN: ${{ secrets.PIMCORE_ENTERPRISE_TOKEN }}
          TORQ_GITHUB_TOKEN: ${{ secrets.TORQ_GITHUB_TOKEN }}
          CONTAINER_REGISTRY: ${{ vars.CONTAINER_REGISTRY }}
          IMAGE: ${{ vars.PHP_FPM_IMAGE }}
          NPM_BUILD: ${{ inputs.NPM_BUILD }}
          RECAPTCHA_CLIENT_KEY: ${{ secrets.RECAPTCHA_CLIENT_KEY }}
          NPM_SPA: ${{ inputs.NPM_SPA }}
          SPA_TWIG: ${{ inputs.SPA_TWIG }}
          PIMCORE_ROOT: ${{ inputs.PIMCORE_ROOT }}

      - name: Build and push supervisord image
        uses: ./reusable-workflow/.github/actions/build-and-push-pimcore-image
        with:
          DOCKERFILE_PATH: ./.docker/Dockerfile
          DOCKERFILE_TARGET: supervisord
          PIMCORE_ENTERPRISE_TOKEN: ${{ secrets.PIMCORE_ENTERPRISE_TOKEN }}
          TORQ_GITHUB_TOKEN: ${{ secrets.TORQ_GITHUB_TOKEN }}
          CONTAINER_REGISTRY: ${{ vars.CONTAINER_REGISTRY }}
          IMAGE: ${{ vars.SUPERVISORD_IMAGE }}
          PIMCORE_ROOT: ${{ inputs.PIMCORE_ROOT }}

  deploy-and-run-init:
    if: ${{ inputs.INIT }}
    runs-on: ${{ inputs.RUNNER || 'ubuntu-latest' }}
    environment: ${{ inputs.ENVIRONMENT }}
    needs:
      - build-and-push-images
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get workflow version
        id: workflow-version
        uses: canonical/get-workflow-version-action@v1
        with:
          repository-name: TorqIT/pimcore-github-actions-workflows
          file-name: container-apps-build-and-deploy.yml
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout workflow repository to use composite actions
        uses: actions/checkout@v4
        with:
          repository: TorqIT/pimcore-github-actions-workflows
          ref: ${{ steps.workflow-version.outputs.sha }}
          path: reusable-workflow
          fetch-depth: 1

      - uses: ./reusable-workflow/.github/actions/container-apps-deploy-and-run-init
        with:
          SERVICE_PRINCIPAL_ID: ${{ secrets.SERVICE_PRINCIPAL_ID }}
          SERVICE_PRINCIPAL_PASSWORD: ${{ secrets.SERVICE_PRINCIPAL_PASSWORD }}
          INIT_IMAGE: ${{ vars.INIT_IMAGE }}
          INIT_CONTAINER_APP_JOB: ${{ vars.INIT_CONTAINER_APP_JOB }}
          RESOURCE_GROUP: ${{ vars.RESOURCE_GROUP }}
          CONTAINER_REGISTRY: ${{ vars.CONTAINER_REGISTRY }}
          TENANT: ${{ vars.TENANT }}
    
  deploy-container-app-revisions:
    runs-on: ${{ inputs.RUNNER || 'ubuntu-latest' }}
    environment: ${{ inputs.ENVIRONMENT }}
    strategy:
      matrix:
        include:
          - image: ${{ vars.PHP_FPM_IMAGE }}
            container-app: ${{ vars.PHP_FPM_CONTAINER_APP }}
            multi-revision: "true"
          - image: ${{ vars.SUPERVISORD_IMAGE }}
            container-app: ${{ vars.SUPERVISORD_CONTAINER_APP }}
            multi-revision: "false"
    needs:
      - build-and-push-images
      - deploy-and-run-init
    if: success() || failure()
    steps:
      # This is a workaround for the fact there is no way to do a conditional "needs"
      - name: Fail fast if necessary jobs failed
        if: ${{ needs.build-and-push-images == 'failure' || needs.build-and-push-images == 'cancelled' || needs.deploy-and-run-init.result == 'failure' || needs.deploy-and-run-init.result == 'cancelled' }}
        run: exit 1

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: ${{ inputs.SUBMODULES }}

      - name: Get workflow version
        id: workflow-version
        uses: canonical/get-workflow-version-action@v1
        with:
          repository-name: TorqIT/pimcore-github-actions-workflows
          file-name: container-apps-build-and-deploy.yml
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout workflow repository to use composite actions
        uses: actions/checkout@v4
        with:
          repository: TorqIT/pimcore-github-actions-workflows
          ref: ${{ steps.workflow-version.outputs.sha }}
          path: reusable-workflow
          fetch-depth: 1

      - uses: ./reusable-workflow/.github/actions/container-apps-deploy-revision
        with:
          TENANT: ${{ vars.TENANT }}
          SERVICE_PRINCIPAL_ID: ${{ secrets.SERVICE_PRINCIPAL_ID }}
          SERVICE_PRINCIPAL_PASSWORD: ${{ secrets.SERVICE_PRINCIPAL_PASSWORD }}
          RESOURCE_GROUP: ${{ vars.RESOURCE_GROUP }}
          CONTAINER_REGISTRY: ${{ vars.CONTAINER_REGISTRY }}
          CONTAINER_APP: ${{ matrix.apps.container-app }}
          MULTI_REVISION: ${{ matrix.apps.multi-revision }}
          IMAGE: ${{ matrix.apps.image }}