# Builds Pimcore Docker images. Useful for verification in continuous integration scenarios, for example:
# on:
#   pull_request:
#     types: [opened, reopened, synchronize]
# jobs:
#   build-images:
#     uses: TorqIT/pimcore-github-actions-workflows/.github/workflows/docker-builds@v7
#     secrets:
#        BUILD_TIME_SECRETS: >
#          {
#            "pimcore-enterprise-token": "${{ secrets.PIMCORE_ENTERPRISE_TOKEN }}",
#            ...any other build-time secrets you need
#          }
#
# Requires the following permissions to be set in the callig job:
# permissions:
#   contents: read
#   actions: read
#

name: Build Docker images

on:
  workflow_call:
    inputs:
      RUNNER:
        required: false
        type: string
        description: Optional self-hosted runner for this workflow (see https://github.com/TorqIT/pimcore-github-actions-workflows#self-hosted-runners)
      NPM_BUILD:
        required: false
        type: boolean
        description: "Whether an NPM build should be run prior to building the PHP image"
      NPM_RUN_CMD:
        required: false
        type: string
        description: "The NPM command that should be run prior to building the PHP image"
      NPM_SPA:
        required: false
        type: boolean
        description: "Whether the NPM build results in a single-page application"
      SPA_TWIG:
        required: false
        type: string
        default: "default/default.html.twig"
        description: "The path to the Twig file where the result of the NPM single-page application build should be copied"
      FRONTEND_ROOT:
        required: false
        type: string
        default: "frontend"
        description: "The path (relative to the project's root) where frontend files are stored"
      SUBMODULES:
        required: false
        type: boolean
        default: false
        description: "Whether to clone submodules when cloning the project repository"
      BUILD_TIME_ARGS:
        required: false
        type: string
        default: "{}"
        description: "A JSON object containing Docker build-time args in key: value format"
      PIMCORE_ROOT:
        required: false
        type: string
        default: "."
        description: "The path (relative to the project's root) in which the Pimcore files are stored (e.g. config, src, etc)"
      INIT_DOCKERFILE:
        required: false
        type: string
        default: ".docker/Dockerfile"
        description: "The path (relative to the project's root) of the Dockerfile used to build the init image"
      INIT_DOCKER_TARGET:
        required: false
        type: string
        default: "init"
        description: "The Docker target to use when building the init image"
      PHP_DOCKERFILE:
        required: false
        type: string
        default: ".docker/Dockerfile"
        description: "The path (relative to the project's root) of the Dockerfile used to build the PHP image"
      PHP_DOCKER_TARGET:
        required: false
        type: string
        default: "php"
        description: "The Docker target to use when building the PHP image"
      SUPERVISORD_DOCKERFILE:
        required: false
        type: string
        default: ".docker/Dockerfile"
        description: "The path (relative to the project's root) of the Dockerfile used to build the supervisord image"
      SUPERVISORD_TARGET:
        required: false
        type: string
        default: "supervisord"
        description: "The Docker target to use when building the supervisord image"

    secrets:
      BUILD_TIME_SECRETS:
        required: false
        description: A JSON object of secrets required at build-time (see above for example format)
      PIMCORE_ENTERPRISE_TOKEN:
        required: false
        description: (Deprecated - use BUILD_TIME_SECRETS instead) The value of your project's Pimcore Enterprise Token
      TORQ_GITHUB_TOKEN:
        required: false
        description: (Deprecated - use BUILD_TIME_SECRETS instead) A GitHub access token used to access private GitHub repositories
      RECAPTCHA_CLIENT_KEY:
        required: false
        description: (Optional) A client key used when building NPM frontends that require ReCAPTCHA

jobs:
  build-docker-images:
    name: Build Docker images
    runs-on: ${{ inputs.RUNNER || 'ubuntu-latest' }}
    environment: ${{ inputs.ENVIRONMENT }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: ${{ inputs.SUBMODULES }}

      - name: Get workflow version
        id: workflow-version
        uses: canonical/get-workflow-version-action@v1
        with:
          repository-name: TorqIT/pimcore-github-actions-workflows
          file-name: docker-builds.yml
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout workflow repository to use composite actions
        uses: actions/checkout@v4
        with:
          repository: TorqIT/pimcore-github-actions-workflows
          ref: ${{ steps.workflow-version.outputs.sha }}
          path: reusable-workflow
          fetch-depth: 1

      - name: Set up Docker
        uses: ./reusable-workflow/.github/actions/setup-docker

      - name: Build init image
        uses: ./reusable-workflow/.github/actions/build-and-push-pimcore-image
        with:
          DOCKERFILE_TARGET: ${{ inputs.INIT_DOCKER_TARGET }}
          DOCKERFILE_PATH: ${{ inputs.INIT_DOCKERFILE }}
          BUILD_TIME_ARGS: ${{ inputs.BUILD_TIME_ARGS }}
          BUILD_TIME_SECRETS: ${{ secrets.BUILD_TIME_SECRETS }}
          PIMCORE_ROOT: ${{ inputs.PIMCORE_ROOT }}
          PIMCORE_ENTERPRISE_TOKEN: ${{ secrets.PIMCORE_ENTERPRISE_TOKEN }}
          TORQ_GITHUB_TOKEN: ${{ secrets.TORQ_GITHUB_TOKEN }}
          PUSH: "false"

      - name: Build PHP image
        uses: ./reusable-workflow/.github/actions/build-and-push-pimcore-image
        with:
          DOCKERFILE_PATH: ${{ inputs.PHP_DOCKERFILE }}
          DOCKERFILE_TARGET: ${{ inputs.PHP_DOCKER_TARGET }}
          BUILD_TIME_ARGS: ${{ inputs.BUILD_TIME_ARGS }}
          BUILD_TIME_SECRETS: ${{ secrets.BUILD_TIME_SECRETS }}
          PIMCORE_ROOT: ${{ inputs.PIMCORE_ROOT }}
          PIMCORE_ENTERPRISE_TOKEN: ${{ secrets.PIMCORE_ENTERPRISE_TOKEN }}
          TORQ_GITHUB_TOKEN: ${{ secrets.TORQ_GITHUB_TOKEN }}
          FRONTEND_ROOT: ${{ inputs.FRONTEND_ROOT }}
          NPM_BUILD: ${{ inputs.NPM_BUILD }}
          RECAPTCHA_CLIENT_KEY: ${{ secrets.RECAPTCHA_CLIENT_KEY }}
          NPM_SPA: ${{ inputs.NPM_SPA }}
          SPA_TWIG: ${{ inputs.SPA_TWIG }}
          NPM_RUN_CMD: ${{ inputs.NPM_RUN_CMD }}
          PUSH: "false"

      - name: Build supervisord image
        uses: ./reusable-workflow/.github/actions/build-and-push-pimcore-image
        with:
          DOCKERFILE_PATH: ${{ inputs.SUPERVISORD_DOCKERFILE }}
          DOCKERFILE_TARGET: ${{ inputs.SUPERVISORD_TARGET }}
          BUILD_TIME_ARGS: ${{ inputs.BUILD_TIME_ARGS }}
          BUILD_TIME_SECRETS: ${{ secrets.BUILD_TIME_SECRETS }}
          PIMCORE_ROOT: ${{ inputs.PIMCORE_ROOT }}
          PIMCORE_ENTERPRISE_TOKEN: ${{ secrets.PIMCORE_ENTERPRISE_TOKEN }}
          TORQ_GITHUB_TOKEN: ${{ secrets.TORQ_GITHUB_TOKEN }}
          PUSH: "false"
