# Merges a Pull Request branch into the develop branch whenever the PR is approved.
# 
# Use the following event trigger to ensure this workflow runs when a review is submitted:
# on:
#   pull_request_review:
#     types: [submitted]
#
# Refer to the README for details on the WORKFLOW parameters.
#

name: Deploy PRs to development environment once approved

on:
  workflow_call:
    inputs:
      RUNNER:
        required: false
        type: string
      DEVELOPMENT_BRANCH:
        required: false
        type: string
        default: 'develop'
    secrets:
      WORKFLOW_APP_ID:
        required: true
      WORKFLOW_PRIVATE_KEY:
        required: true

jobs:
  merge-pr-to-dev:
    uses: TorqIT/github-actions-workflows/.github/workflows/merge-prs-to-dev.yml@v0
    with:
      RUNNER: ${{ inputs.RUNNER }}
      DEVELOPMENT_BRANCH: ${{ inputs.DEVELOPMENT_BRANCH }}
    secrets: 
      WORKFLOW_APP_ID: ${{ secrets.WORKFLOW_APP_ID }}
      WORKFLOW_PRIVATE_KEY: ${{ secrets.WORKFLOW_PRIVATE_KEY }}