# META - not reusable, runs directly on this repository

name: Update major release tag

on:
  release:
    types: [created]

jobs:
  tag-major-release:
    uses: TorqIT/github-actions-workflows/.github/workflows/update-major-release-tag.yml@v1