# Resets the develop branch to match the main branch.
# 
# In typical situations, you would want to run this on a schedule such as the following which will 
# trigger the workflow at midnight every Sunday:
# on:
#   schedule:
#     - cron: "0 0 * * SUN"
#
# Refer to the README for details on the WORKFLOW parameters.
#

name: Reset develop branch to match main

on:
  workflow_call:
    inputs:
      RUNNER:
        required: false
        type: string
    secrets:
      WORKFLOW_APP_ID:
        required: true
      WORKFLOW_PRIVATE_KEY:
        required: true

jobs:
  merge-pr-to-dev:
    uses: TorqIT/github-actions-workflows/.github/workflows/reset-dev-to-main.yml@v0
    with:
      RUNNER: ${{ inputs.RUNNER }}
    secrets: 
      WORKFLOW_APP_ID: ${{ secrets.WORKFLOW_APP_ID }}
      WORKFLOW_PRIVATE_KEY: ${{ secrets.WORKFLOW_PRIVATE_KEY }}
