name: Run coding standards

on:
  workflow_call:
    inputs:
      RUNNER:
        required: false
        type: string
      REUSABLE_WORKFLOW_REF:
        required: false
        type: string

jobs:
  tests:
    runs-on: ${{ inputs.RUNNER || 'ubuntu-latest' }}

    env:
      TAG: ${{ github.run_id }}

    steps:
      # Checkout the caller repository as usual

      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          path: app

      # Checkout the workflow repository itself so that we can access the extra script files
      - name: Checkout workflow repository
        uses: actions/checkout@v4
        with:
          repository: TorqIT/pimcore-github-actions-workflows
          ref: ${{ inputs.REUSABLE_WORKFLOW_REF }}
          path: reusable-workflow

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2

      - name: Install Composer dependencies
        run: composer install
        working-directory: app/pimcore-root

      - name: List Files
        run: ls -la
        working-directory: app/pimcore-root

      - name: Move ecs.php file
        run: mv reusable-workflow/.ecs.php app/pimcore-root

      - name: Coding Standards Check
        run: vendor/bin/ecs check src
        working-directory: app/pimcore-root
