# Runs tests which are assumed to be defined in a docker-compose.test.yml. 
# Typically these are run on Pull Requests, in which case you can trigger this workflow as follows:
# on:
#   pull_request:
#     types: [opened, reopened, synchronize]

name: Run tests

on:
  workflow_call:
    inputs:
      RUNNER:
        required: false
        type: string

jobs:
  tests:
    runs-on: ${{ inputs.RUNNER || 'ubuntu-latest' }}

    steps:
      - uses: actions/checkout@v3

      # Checkout the workflow directory so that we can get access to the extra script files
      - uses: actions/checkout@v3
        with:
          repository: TorqIT/pimcore-github-actions-workflows
          ref: feat/better-pr-tests
          path: reusable-workflow

      - name: Build test container
        run: docker-compose -f ./reusable-workflow/scripts/run-tests/docker-compose.yml build

      - name: Run tests
        run: docker-compose -f ./reusable-workflow/scripts/run-tests/docker-compose.yml run tests

      - name: Bring down the containers
        if: always()
        run: docker-compose -f  ./reusable-workflow/scripts/run-tests/docker-compose.yml down