# Runs Pimcore tests. Typically these are run on Pull Requests, in which case you can trigger this workflow as follows:
# on:
#   pull_request:
#     types: [opened, reopened, synchronize]
# 
# As this workflow needs to access some scripts located in this repo, you must specify a Git ref as an input. In most cases, this can simply be the same
# ref as the one you are using to call the workflow - e.g.:
# jobs:
# unit-tests-on-pr:
#   uses: TorqIT/pimcore-github-actions-workflows/.github/workflows/run-tests.yml@v2
#   with:
#     REUSABLE_WORKFLOW_REF: v2
# 
# Note this workflow assumes there is a buildable PHP-FPM Docker image located in the /docker/php-fpm directory of the calling repository.

name: Run coding standards

on:
  workflow_call:
    inputs:
      RUNNER:
        required: false
        type: string
      REUSABLE_WORKFLOW_REF:
        required: false
        type: string

jobs:
  tests:
    runs-on: ${{ inputs.RUNNER || 'ubuntu-latest' }}

    env:
      TAG: ${{ github.run_id }}

    steps:
      # Checkout the caller repository as usual
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      # Checkout the workflow repository itself so that we can access the extra script files
      - name: Checkout workflow repository
        uses: actions/checkout@v4
        with:
          repository: TorqIT/pimcore-github-actions-workflows
          ref: ${{ inputs.REUSABLE_WORKFLOW_REF }}
          path: reusable-workflow
      
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3

      - name: Install Coding Standards package
        run: composer require symplify/easy-coding-standard 

      - name: Coding Standards Check
        run: vendor/bin/ecs check src
