# Runs tests which are assumed to be defined in a docker-compose.test.yml. 
# Typically these are run on Pull Requests, in which case you can trigger this workflow as follows:
# on:
#   pull_request:
#     types: [opened, reopened, ready_for_review, synchronize]

name: Run tests

on:
  workflow_call:
    inputs:
      RUNNER:
        required: false
        type: string

jobs:
  tests:
    runs-on: ${{ inputs.RUNNER || 'ubuntu-latest' }}

    steps:
      - uses: actions/checkout@v3

      - name: Build test container
        run: docker-compose -f ./docker/test/docker-compose.test.yml build

      - name: Run tests
        run: docker-compose -f ./docker/test/docker-compose.test.yml run tests

      - name: Bring down the containers
        if: always()
        run: docker-compose -f ./docker/test/docker-compose.test.yml down
