# Creates or moves the "major" release tag to point to the latest release (based on the release's set tag). For example - creating a
# release tagged v1.0.0 will create the v1 tag and point it to the same commit. Similarly, if we later create v1.3.2,
# this action will move the existing v1 tag to point to this latest release.
#
# To trigger this workflow when a release is created, use the following:
# on:
#   release:
#     types: [created]

on:
  workflow_call:
    inputs:
      RUNNER:
        required: false
        type: string

jobs:
  tag-major-release:
    runs-on: ${{ inputs.RUNNER || 'ubuntu-latest' }}

    steps:
      - uses: actions/checkout@v4

      - name: Get major version number and update tag
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          MAJOR=${VERSION%%.*}
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git tag -fa ${MAJOR} -m "Update major version tag"
          git push origin ${MAJOR} --force
